name: Create staging promotion pull request
on:
  push:
    branches:
      - master
jobs:
  stagingPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging
      - name: Reset promotion branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          branch: staging-promotion
          labels: enhancement
