on: [push]
jobs:
  linter-action:
    runs-on: ubuntu-latest
    name: Linter action
    steps:
      - uses: actions/checkout@v2
      - name: Linter action
        id: linter
        uses: AntonKornus/TypeScript-Linter@master
