on: [push]
jobs:
  linter-action:
    runs-on: ubuntu-latest
    name: Linter action
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Linter action
        id: linter
        uses: AntonKornus/hello-world-action@master
      - name: Linter result
        run: echo "Result ${{ steps.linter.outputs.result }}"
